apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customdeployments.crd.suaas21.com
spec:
  group: crd.suaas21.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: customdeployments
    singular: customdeployment
    kind: CustomDeployment
    shortNames:
      - csd